import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { X, Mail, Send, Loader2, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/use-toast";
import { getCenterHubLabel } from "@/lib/constants";

const ADMIN_EMAIL = "colonnamedia@gmail.com";

export default function EmailResultsModal({ business, draft, branches, stages, objectives, onClose }) {
  const { toast } = useToast();
  const [email, setEmail] = useState(business?.created_by || "");
  const [clientName, setClientName] = useState(business?.business_name || "");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);

  const buildEmailBody = () => {
    const hub = getCenterHubLabel(business?.storefront_type);
    const activeBranches = branches.filter(b => b.visible !== false && (b.purpose || b.objective));

    return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
  body { font-family: Arial, sans-serif; color: #111; background: #fff; }
  .header { background: linear-gradient(135deg, #6d28d9, #2563eb); color: white; padding: 32px; border-radius: 12px 12px 0 0; }
  .section { padding: 24px; border-bottom: 1px solid #e5e7eb; }
  .tag { display: inline-block; background: #f3f4f6; padding: 4px 10px; border-radius: 20px; font-size: 12px; margin: 2px; }
  .channel { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 8px 0; }
  .metric { font-size: 12px; color: #6b7280; }
  .highlight { color: #6d28d9; font-weight: bold; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f3f4f6; padding: 8px 12px; text-align: left; font-size: 13px; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
  .footer { background: #1f2937; color: #9ca3af; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; font-size: 12px; }
</style></head>
<body>
<div style="max-width:600px;margin:0 auto;">

<div class="header">
  <h1 style="margin:0;font-size:24px;">📋 Business Marketing Blueprint</h1>
  <p style="margin:8px 0 0;opacity:0.85;">Your complete marketing home base — generated by Blueprint Builder</p>
</div>

<div class="section" style="background:#faf5ff;">
  <h2 style="margin:0 0 16px;color:#6d28d9;">Strategy Snapshot</h2>
  <div style="display:grid;gap:8px;">
    <p><strong>Business:</strong> ${business?.business_name}</p>
    <p><strong>Type:</strong> ${business?.business_type || "—"} &bull; ${business?.industry || "—"}</p>
    <p><strong>Main Goal:</strong> ${business?.main_goal || "—"}</p>
    <p><strong>Center Hub:</strong> ${hub}</p>
    <p><strong>Target Audience:</strong> ${business?.target_audience || "—"}</p>
    <p style="font-weight:bold;color:#6d28d9;font-size:15px;">Traffic → Conversion → Follow-Up → Sales</p>
  </div>
</div>

<div class="section">
  <h2 style="margin:0 0 16px;">Primary Marketing Channels</h2>
  ${activeBranches.map(b => `
  <div class="channel">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
      <strong style="font-size:15px;">${b.branch_name}</strong>
      <span class="tag">${b.priority_level || "medium"} priority</span>
    </div>
    ${b.purpose ? `<p class="metric">Purpose: ${b.purpose}</p>` : ""}
    ${b.objective ? `<p class="metric">Objective: ${b.objective}</p>` : ""}
    <div style="display:flex;gap:16px;margin-top:4px;">
      <span class="metric">⏱ Time: ${b.time_percent || 0}%</span>
      <span class="metric">💰 Cost: ${b.cost_percent || 0}%</span>
      ${b.owner ? `<span class="metric">👤 ${b.owner.replace("_", " ")}</span>` : ""}
    </div>
    ${b.metric_to_watch ? `<p class="metric" style="margin-top:6px;">📊 Metric: ${b.metric_to_watch}</p>` : ""}
    ${b.what_to_adjust_if_weak ? `<p class="metric">🔧 If Weak: ${b.what_to_adjust_if_weak}</p>` : ""}
  </div>`).join("")}
</div>

${stages.length > 0 ? `
<div class="section">
  <h2 style="margin:0 0 12px;">Customer Journey Map</h2>
  <p style="margin:0 0 16px;color:#6b7280;font-size:13px;">${stages.map(s => s.stage_name).join(" → ")}</p>
  ${stages.filter(s => s.stage_description || s.supporting_channel).map(s => `
  <div style="margin-bottom:12px;padding-left:16px;border-left:3px solid #6d28d9;">
    <strong style="font-size:13px;">${s.stage_name}</strong>
    ${s.stage_description ? `<p style="margin:4px 0;font-size:13px;color:#4b5563;">${s.stage_description}</p>` : ""}
    ${s.supporting_channel ? `<p class="metric">Channel: ${s.supporting_channel}</p>` : ""}
    ${s.dropoff_risk ? `<p style="color:#dc2626;font-size:12px;">⚠️ Risk: ${s.dropoff_risk}</p>` : ""}
  </div>`).join("")}
</div>` : ""}

<div class="section">
  <h2 style="margin:0 0 16px;">Time & Cost Allocation</h2>
  <table>
    <thead><tr><th>Channel</th><th>Time %</th><th>Cost %</th></tr></thead>
    <tbody>
      ${branches.map(b => `<tr><td>${b.branch_name}</td><td>${b.time_percent || 0}%</td><td>${b.cost_percent || 0}%</td></tr>`).join("")}
    </tbody>
  </table>
</div>

<div class="section" style="background:#f0fdf4;">
  <h2 style="margin:0 0 12px;">Weekly Review Plan</h2>
  <ul style="color:#374151;font-size:13px;line-height:2;">
    <li>Run this plan for ${draft?.testing_period_days || 7} days</li>
    <li>Review the main bottleneck</li>
    <li>Adjust only ${draft?.max_variables_to_adjust || 2} variable(s)</li>
    <li>Do not restart the entire system</li>
    <li>Return to the blueprint when results feel unclear</li>
  </ul>
</div>

<div class="footer">
  Generated by Marketing Blueprint Builder &bull; This is your marketing home base
</div>

</div>
</body></html>`;
  };

  const handleSend = async () => {
    if (!email) return;
    setSending(true);

    const subject = `📋 Your Marketing Blueprint — ${business?.business_name}`;
    const body = buildEmailBody();

    // Send to client
    await base44.integrations.Core.SendEmail({ to: email, subject, body });

    // Notify admin if it was a paid purchase
    if (draft?.payment_status === "paid") {
      await base44.integrations.Core.SendEmail({
        to: ADMIN_EMAIL,
        subject: `💳 New Blueprint Purchase — ${business?.business_name}`,
        body: `
          <div style="font-family:Arial;padding:20px;">
            <h2>New Blueprint Purchase</h2>
            <p><strong>Business:</strong> ${business?.business_name}</p>
            <p><strong>Industry:</strong> ${business?.industry || "N/A"}</p>
            <p><strong>Client Email:</strong> ${email}</p>
            <p><strong>Goal:</strong> ${business?.main_goal || "N/A"}</p>
            <p><strong>Draft ID:</strong> ${draft?.id}</p>
            <p style="color:#16a34a;font-weight:bold;">Payment Status: PAID</p>
          </div>
        `,
      });
    }

    setSending(false);
    setSent(true);
    toast({ title: "Blueprint sent!", description: `Results emailed to ${email}` });
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-card rounded-2xl w-full max-w-md shadow-2xl" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <div className="flex items-center gap-2">
            <Mail className="w-5 h-5 text-primary" />
            <h3 className="font-display font-semibold text-lg">Email Blueprint Results</h3>
          </div>
          <button onClick={onClose}><X className="w-5 h-5 text-muted-foreground" /></button>
        </div>

        {sent ? (
          <div className="p-8 text-center">
            <CheckCircle className="w-14 h-14 text-emerald-500 mx-auto mb-4" />
            <h3 className="font-semibold text-lg mb-2">Blueprint Sent!</h3>
            <p className="text-muted-foreground text-sm">Your complete marketing blueprint has been emailed to {email}</p>
            <Button className="mt-6 w-full" onClick={onClose}>Done</Button>
          </div>
        ) : (
          <div className="p-6 space-y-4">
            <p className="text-sm text-muted-foreground">
              Send the complete marketing blueprint including channels, customer journey, allocations, and weekly plan to any email address.
            </p>
            <div className="space-y-1.5">
              <Label>Client / Recipient Email</Label>
              <Input
                type="email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                placeholder="client@example.com"
              />
            </div>
            <div className="bg-muted/50 rounded-lg p-3 text-xs text-muted-foreground space-y-1">
              <p>✓ Full channel details with purpose, objective, metrics</p>
              <p>✓ Customer journey map with all stages</p>
              <p>✓ Time & cost allocation table</p>
              <p>✓ Weekly review framework</p>
            </div>
            <Button
              className="w-full gap-2"
              onClick={handleSend}
              disabled={sending || !email}
            >
              {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              {sending ? "Sending..." : "Send Blueprint"}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}